name: Windows_Container_Workflow

on:
  workflow_dispatch:

env:
  RUNNER_VERSION: 2.323.0

jobs:
  build-and-push:
    runs-on: windows-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4.2.2


      - name: "Build and push image"
        uses: azure/docker-login@v2
        with:
          login-server: docker.io
          username: frank15ortiz
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker login docker.io -u frank15ortiz -p ${{ secrets.REGISTRY_PASSWORD }}
          docker build --build-arg RUNNER_VERSION=${{ env.RUNNER_VERSION }} -t frank15ortiz/windows-runners:${{ env.RUNNER_VERSION }} .
          docker push frank15ortiz/windows-runners:${{ env.RUNNER_VERSION }}
